# Change these first
owner: amjadalfawal # Your GitHub organization or username, where this repository lives
repo: UptimeBahar # The name of this repository

sites:
  - name: Google
    url: https://www.google.com
  - name: BaharErp
    url: https://erp.bahargroup.net
  - name: BaharIsell
    url: https://bahar.isell360platform.com
    
status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  baseUrl: /UptimeBahar


# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
